version: '3.8'

services:
  config-server:
    build: ./config-server
    container_name: nexhub-config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_APPLICATION_NAME=config-server
      - SERVER_PORT=8888
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=classpath:/configs/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
    networks:
      - next-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  discovery-service:
    build: ./discovery-service
    container_name: nexhub-discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_APPLICATION_NAME=discovery-service
      - SERVER_PORT=8761
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_INSTANCE_HOSTNAME=discovery-service
      - EUREKA_INSTANCE_PREFER_IP=false
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
      - EUREKA_SERVER_EVICTION_INTERVAL=10000
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - next-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-gateway:
    build: ./api-gateway
    container_name: nexhub-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_APPLICATION_NAME=api-gateway
      - SERVER_PORT=8080
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_HOSTNAME=api-gateway
      - EUREKA_INSTANCE_PREFER_IP=false
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080,http://localhost:5731
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers
      - CORS_ALLOW_CREDENTIALS=true
      - AUTH_SERVICE_URI=lb://auth-service
      - USER_SERVICE_URI=lb://user-service
      - NOTIFICATION_SERVICE_URI=lb://notification-service
      - BLOG_SERVICE_URI=lb://blog-service
      - WARRANTY_SERVICE_URI=lb://warranty-service
      - PRODUCT_SERVICE_URI=lb://product-service
      - LANGUAGE_SERVICE_URI=lb://language-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - next-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  auth-service:
    build: ./auth-service
    container_name: nexhub-auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_APPLICATION_NAME=auth-service
      - SERVER_PORT=8081
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_HOSTNAME=auth-service
      - EUREKA_INSTANCE_PREFER_IP=false
      - DATABASE_URL=jdbc:postgresql://postgres:5432/nexhub_auth
      - DATABASE_USERNAME=nexhub
      - DATABASE_PASSWORD=nexhub123
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - next-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  postgres:
    image: postgres:15-alpine
    container_name: nexhub-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nexhub_auth
      - POSTGRES_USER=nexhub
      - POSTGRES_PASSWORD=nexhub123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - next-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexhub -d nexhub_auth"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  next-network:
    driver: bridge

volumes:
  postgres_data: