version: '3.8'

services:
  config-server:
    build: ./config-server
    container_name: nexhub-config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_APPLICATION_NAME=config-server
      - SERVER_PORT=8888
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=classpath:/configs/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
    networks:
      - next-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-gateway:
    build: ./api-gateway
    container_name: nexhub-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_APPLICATION_NAME=api-gateway
      - SERVER_PORT=8080
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080,http://localhost:5731
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers
      - CORS_ALLOW_CREDENTIALS=true
      - AUTH_SERVICE_URI=lb://auth-service
      - USER_SERVICE_URI=lb://user-service
      - NOTIFICATION_SERVICE_URI=lb://notification-service
      - BLOG_SERVICE_URI=lb://blog-service
      - WARRANTY_SERVICE_URI=lb://warranty-service
      - PRODUCT_SERVICE_URI=lb://product-service
      - LANGUAGE_SERVICE_URI=lb://language-service
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - next-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  next-network:
    driver: bridge