server:
  port: ${SERVER_PORT}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP}
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  server:
    enable-self-preservation: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION}
    eviction-interval-timer-in-ms: ${EUREKA_SERVER_EVICTION_INTERVAL}