server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/nexhub_user}
    username: ${DATABASE_USERNAME:nexhub}
    password: ${DATABASE_PASSWORD:nexhub123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
    path: /swagger-ui.html
    try-it-out-enabled: true
    persist-authorization: true
    display-request-duration: true
  packages-to-scan: com.devwonder.user_service.controller

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP}
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  server:
    enable-self-preservation: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION}
    eviction-interval-timer-in-ms: ${EUREKA_SERVER_EVICTION_INTERVAL}